title: Ellington Hemphill
email: hemphilled@icloud.com
description: Personal site
url: https://apollo1291.github.io
baseurl: /me

markdown: kramdown
kramdown:
  parse_block_html: true
  parse_span_html: true
  input: GFM
  math_engine: mathjax

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - "Ellington Hemphill Resume.pdf"

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "blog/*/blog.md"
    values:
      layout: post
